environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

build: off

test_script:
  - "%PYTHON%\\python.exe -m unittest discover -s tests"
